
export const CREATE_CORPORATION_USER_SUCCESS = "CREATE_CORPORATION_USER_SUCCESS";
export const CREATE_CORPORATION_USER_FAILED = "CREATE_CORPORATION_USER_FAILED";

export const CREATE_CORPORARTION_USER_AND_BOOKING_SUCCESS = "CREATE_CORPORARTION_USER_AND_BOOKING_SUCCESS";
export const CREATE_CORPORARTION_USER_AND_BOOKING_FAILED = "CREATE_CORPORARTION_USER_AND_BOOKING_FAILED";

export const UPDATE_CORPORATION_USER_SUCCESS = "UPDATE_CORPORATION_USER_SUCCESS";
export const UPDATE_CORPORATION_USER_FAILED = "UPDATE_CORPORATION_USER_FAILED";

export const DELETE_CORPORATION_USER_SUCCESS = "DELETE_CORPORATION_USER_SUCCESS";
export const DELETE_CORPORATION_USER_FAILED = "DELETE_CORPORATION_USER_FAILED";


