
export const booking =
    {
        id: "",
        label: "Ny",
        staffType: "",
        numberOfStaff: 0,
        date: new Date(),
        startTime: "",
        endTime: "",
        contactPerson: "",
        phoneNumber: "",
        address: "",
        zipCode: "",
        arrangementType: "",
        arrangementTypeOther: "",
        extraWorkHours: "",
        foodIncluded: "",
        jobDescription: "",
        accessInformation: "",
        upperDressCode: "",
        upperDressCodeOther: "",
        lowerDressCode: "",
        lowerDressCodeOther: "",
        shoesDressCode: "",
        shoesDressCodeOther: "",
        itemToBring: "",
        languageSkill: "",
        staffGender: "",
        jobExperience: "",
        transportWage: "",
        hourlyWage: "",
        wageTotal: "",
        priceTotal: "",
    };
