
export const CREATE_CORPORATION_USER_SUCCESS = "CREATE_CORPORATION_USER_SUCCESS";
export const CREATE_CORPORATION_USER_FAILED = "CREATE_CORPORATION_USER_FAILED";

export const DELETE_CORPORATION_USER_SUCCESS = "DELETE_CORPORATION_USER_SUCCESS";
export const DELETE_CORPORATION_USER_FAILED = "DELETE_CORPORATION_USER_FAILED";


